// Generated by gencpp from file BankService/ops1Response.msg
// DO NOT EDIT!


#ifndef BANKSERVICE_MESSAGE_OPS1RESPONSE_H
#define BANKSERVICE_MESSAGE_OPS1RESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace BankService
{
template <class ContainerAllocator>
struct ops1Response_
{
  typedef ops1Response_<ContainerAllocator> Type;

  ops1Response_()
    : result()  {
    }
  ops1Response_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::BankService::ops1Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::BankService::ops1Response_<ContainerAllocator> const> ConstPtr;

}; // struct ops1Response_

typedef ::BankService::ops1Response_<std::allocator<void> > ops1Response;

typedef boost::shared_ptr< ::BankService::ops1Response > ops1ResponsePtr;
typedef boost::shared_ptr< ::BankService::ops1Response const> ops1ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::BankService::ops1Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::BankService::ops1Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::BankService::ops1Response_<ContainerAllocator1> & lhs, const ::BankService::ops1Response_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::BankService::ops1Response_<ContainerAllocator1> & lhs, const ::BankService::ops1Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace BankService

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::BankService::ops1Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BankService::ops1Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::BankService::ops1Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::BankService::ops1Response_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BankService::ops1Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BankService::ops1Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::BankService::ops1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::BankService::ops1Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::BankService::ops1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BankService/ops1Response";
  }

  static const char* value(const ::BankService::ops1Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::BankService::ops1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
;
  }

  static const char* value(const ::BankService::ops1Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::BankService::ops1Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ops1Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::BankService::ops1Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::BankService::ops1Response_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BANKSERVICE_MESSAGE_OPS1RESPONSE_H
