// Generated by gencpp from file BankService/ops1.msg
// DO NOT EDIT!


#ifndef BANKSERVICE_MESSAGE_OPS1_H
#define BANKSERVICE_MESSAGE_OPS1_H

#include <ros/service_traits.h>


#include <BankService/ops1Request.h>
#include <BankService/ops1Response.h>


namespace BankService
{

struct ops1
{

typedef ops1Request Request;
typedef ops1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ops1
} // namespace BankService


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::BankService::ops1 > {
  static const char* value()
  {
    return "2c0fa4564a7bae7c28ac5a5f4bafcf82";
  }

  static const char* value(const ::BankService::ops1&) { return value(); }
};

template<>
struct DataType< ::BankService::ops1 > {
  static const char* value()
  {
    return "BankService/ops1";
  }

  static const char* value(const ::BankService::ops1&) { return value(); }
};


// service_traits::MD5Sum< ::BankService::ops1Request> should match
// service_traits::MD5Sum< ::BankService::ops1 >
template<>
struct MD5Sum< ::BankService::ops1Request>
{
  static const char* value()
  {
    return MD5Sum< ::BankService::ops1 >::value();
  }
  static const char* value(const ::BankService::ops1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::BankService::ops1Request> should match
// service_traits::DataType< ::BankService::ops1 >
template<>
struct DataType< ::BankService::ops1Request>
{
  static const char* value()
  {
    return DataType< ::BankService::ops1 >::value();
  }
  static const char* value(const ::BankService::ops1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::BankService::ops1Response> should match
// service_traits::MD5Sum< ::BankService::ops1 >
template<>
struct MD5Sum< ::BankService::ops1Response>
{
  static const char* value()
  {
    return MD5Sum< ::BankService::ops1 >::value();
  }
  static const char* value(const ::BankService::ops1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::BankService::ops1Response> should match
// service_traits::DataType< ::BankService::ops1 >
template<>
struct DataType< ::BankService::ops1Response>
{
  static const char* value()
  {
    return DataType< ::BankService::ops1 >::value();
  }
  static const char* value(const ::BankService::ops1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BANKSERVICE_MESSAGE_OPS1_H
